name: 'release'

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Docker Login
      run: docker login docker.pkg.github.com -u zelda-rageux -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Build
      run: docker build --tag docker.pkg.github.com/zelda-rageux/docker-smtp/smtp:${{ steps.get_version.outputs.VERSION }} .
    - name: Docker Publish
      run: docker push docker.pkg.github.com/zelda-rageux/docker-smtp/smtp:${{ steps.get_version.outputs.VERSION }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
